can_ports: ["can0", "can1"]
max_current_A: 2
has_endstop: true
move_to_position_tolerance_rad: 0.01
homing_method: "next_index"
calibration:
    endstop_search_torques_Nm: [-0.1, -0.1, +0.1]
    move_steps: 500
safety_kd: [0.08, 0.08, 0.04]
position_control_gains:
    kp: [6, 6, 6]
    kd: [0.01, 0.01, 0.01]
hard_position_limits_lower: [-1.8, -1.6, -3.3]
hard_position_limits_upper: [1.8, 4.7, 3.3]
soft_position_limits_lower: [-1.6, -1.4, -3.1]
soft_position_limits_upper: [1.6, 4.5, 3.1]

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad: [-0.125, -0.894, 1.164]
initial_position_rad: [0.0, 0.0, -1.5707]
