can_ports: ["can0", "can1"]
max_current_A: 2
has_endstop: false
move_to_position_tolerance_rad: 0.01
homing_method: "next_index"
#homing_method: "current_position"
calibration:
    endstop_search_torques_Nm: [-0.1, -0.1, +0.1]
    move_steps: 1500
safety_kd: [0.005, 0.005, 0.005]
position_control_gains:
    kp: [5, 5, 2]
    kd: [0.015, 0.015, 0.015]
hard_position_limits_lower: [-1.8, -1.6, -3.3]
hard_position_limits_upper: [1.8, 4.7, 3.3]
soft_position_limits_lower: [-1.6, -1.4, -3.1]
soft_position_limits_upper: [1.6, 4.5, 3.1]

# Set zero-position according to URDF (finger pointing straight down).
#home_offset_rad: [0, 0, 0]
#initial_position_rad: [0.0, 0.0, 0.0]

home_offset_rad: [-0.162, -0.894, 1.154]  # strictly for finger 0
initial_position_rad: [0, 0.8, -1.5707]   # strictly for finger 0

#home_offset_rad: [-0.16, -0.877, 1.8485]  # strictly for finger 2
#initial_position_rad: [0, 0.8, -1.5707]    # strictly for finger 2
#initial_position_rad: [0, 1.0, -2.0]   # strictly for finger 0

