can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2.0

has_endstop: true
homing_method: "current_position"

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad: [1.593, 1.380, 2.851, 1.593, 1.380, 2.851, 1.593, 1.380, 2.851]

move_to_position_tolerance_rad: 0.05
calibration:
    endstop_search_torques_Nm: 
        - -0.22
        - -0.22
        - -0.22
        - -0.22
        - -0.22
        - -0.22
        - -0.22
        - -0.22
        - -0.22
    move_steps: 500
safety_kd:
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
position_control_gains:
    kp: [6, 6, 6, 6, 6, 6, 6, 6, 6]
    kd: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]

hard_position_limits_lower: [-1.8, -1.4, -3.1, -1.8, -1.4, -3.1, -1.8, -1.4, -3.1]
hard_position_limits_upper: [1.8, 4.5, 3.1, 1.8, 4.5, 3.1, 1.8, 4.5, 3.1]

# Set the initial position such that it is still save when the stage is at the
# highest level.
initial_position_rad:
    - 0
    - -0.9
    - -1.7
    - 0
    - -0.9
    - -1.7
    - 0
    - -0.9
    - -1.7
