can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2.0
has_endstop: true
move_to_position_tolerance_rad: 0.05
homing_method: "next_index"
calibration:
    endstop_search_torques_Nm: 
        - -0.1
        - -0.1
        - +0.1
        - -0.1
        - -0.1
        - +0.1
        - -0.1
        - -0.1
        - +0.1
    move_steps: 500
safety_kd:
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
position_control_gains:
    kp: [4, 4, 4, 4, 4, 4, 4, 4, 4]
    kd: [0.015, 0.015, 0.015, 0.015, 0.015, 0.015, 0.015, 0.015, 0.015]

hard_position_limits_lower:
    - -2.0
    - -1.4
    - -3.2
    - -2.0
    - -1.4
    - -3.2
    - -2.0
    - -1.4
    - -3.2
hard_position_limits_upper:
    - 1.6
    - 1.8
    - 3.2
    - 1.6
    - 1.8
    - 3.2
    - 1.6
    - 1.8
    - 3.2

soft_position_limits_lower:
    - -1.6
    - -1.2
    - -3.0
    - -1.6
    - -1.2
    - -3.0
    - -1.6
    - -1.2
    - -3.0
soft_position_limits_upper:
    - 1.0
    - 1.6
    - 3.0
    - 1.0
    - 1.6
    - 3.0
    - 1.0
    - 1.6
    - 3.0

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad: [-0.125, -0.894, 1.164, -0.192, -1.223, 1.6405, -0.186, -0.864, 1.8485]
initial_position_rad: [0, 0.8, -1.5707, 0, 0.8, -1.5707, 0, 0.8, -1.5707]

# for no homing
home_offset_rad: [0, 0, 0, 0, 0, 0, 0, 0, 0]
initial_position_rad: [0, 0, 0, 0, 0, 0, 0, 0, 0]

